#!/bin/sh -f
###### This run file is generated by Pegasus UI
###### Pegasus Version 23.10-p015

/grid/tfo/tools2/PEGASUS231_23.10.000/bin/pegasus \
	--dp 4 \
	--log_dir LOGS \
	-top_cell CELLNAME \
	-ui_data -interactive \
	-run_dir DRC_sky130 \
	--control ./drc_CTL.pvl \
	$PEGASUS_DRC/sky130_rev_0.0_2.9.drc.pvl


